dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign' // 서비스 간 HTTP API 호출 위해 사용.
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocVersion}"
    testImplementation 'org.springframework.batch:spring-batch-test'
    runtimeOnly 'com.h2database:h2'
}

bootJar {
    enabled = true
}

jar {
    enabled = false
}
