services:
  mopl-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kestrel71/mopl:latest
    container_name: mopl-app
    ports:
      - "80:8080" # EC2 80 -> Spring 8080
    restart: always
    depends_on:
      mopl-db:
        condition: service_healthy
      mopl-redis:
        condition: service_healthy
    env_file:
      - .env

  mopl-db:
    image: postgres:17-alpine
    container_name: mopl-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  mopl-redis:
    image: redis:7.2-alpine
    container_name: mopl-redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: