mopl:
  api:
    tmdb:
      key: ${TMDB_API_KEY:mock}
      url: ${TMDB_API_URL:https://api.themoviedb.org/3}
    sportsdb:
      key: ${SPORTSDB_API_KEY:mock}
      url: ${SPORTSDB_API_URL:https://www.thesportsdb.com/api/v1/json}
  batch:
    cron: ${BATCH_CRON_SCHEDULE:0 0 3 * * ?}
