spring:
  datasource:
    url: jdbc:postgresql://${DB_ENDPOINT_NOTIFICATION}:5432/${DB_NAME_NOTIFICATION}
    username: ${DB_USERNAME_NOTIFICATION}
    password: ${DB_PASSWORD_NOTIFICATION}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true
