server:
  port: 8086

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    notification:
      url: jdbc:postgresql://${DB_ENDPOINT}:5432/${DB_NAME_NOTIFICATION}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

  jpa:
    notification:
      hibernate:
        ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: false
