spring:
  config:
    import:
      - optional:classpath:/application-user-dev.yml
      - optional:classpath:/application-content-dev.yml
      - optional:classpath:/application-playlist-dev.yml
      - optional:classpath:/application-batch-dev.yml
      - optional:classpath:/application-notification-dev.yml
      - optional:classpath:/application-image-dev.yml
