server:
  port: 8081
  forward-headers-strategy: framework

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    user:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
  jpa:
    user:
      hibernate:
        ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
          kakao:
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"