spring:
  application:
    name: mopl-user
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    locations: classpath:db/migration
  mail:
    host: ${mopl.mail.host}
    port: ${mopl.mail.port}
    username: ${mopl.mail.username}
    password: ${mopl.mail.password}
    properties:
      mail:
        smtp:
          auth: ${mopl.mail.properties.mail.smtp.auth}
          starttls:
            enable: ${mopl.mail.properties.mail.smtp.starttls.enable}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile,email # 제공자의 서비스 scope. OIDC 비활성화 및 CustomOAuth2UserService 사용
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

mopl:
  account:
    password-policy: "bcrypt"
    temp-password-policy: "fixed"
    temp-password-reset-timeout-policy-in-minutes: 3
  storage:
    aws:
      region: ${AWS_REGION:ap-northeast-2}
      bucket-name: ${AWS_S3_BUCKET}
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
      signature-duration-in-hours: 1 # Presigned URL 유효기간
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jwt:
    access-token:
      secret: ${JWT_ACCESS_TOKEN_SECRET:sb06-mopl-team03-jwt-temporary-secret}
      expiration-ms: ${ACCESS_TOKEN_EXPIRATION_MS:300000}
    refresh-token:
      secret: ${JWT_REFRESH_TOKEN_SECRET:sb06-mopl-team03-jwt-temporary-secret}
      expiration-ms: ${REFRESH_TOKEN_EXPIRATION_MS:604800000}
    max-session: ${JWT_MAX_SESSION:1}


management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
