spring:
  application:
    name: mopl-content
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual

mopl:
  storage:
    aws:
      region: ${AWS_REGION:ap-northeast-2}
      bucket-name: ${AWS_S3_BUCKET}
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
      signature-duration-in-hours: 1 # Presigned URL 유효기간

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
