spring:
  datasource:
    url: jdbc:postgresql://${DB_ENDPOINT}:5432/${DB_NAME_CONTENT}
    username: ${DB_USERNAME_CONTENT}
    password: ${DB_PASSWORD_CONTENT}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true
