server:
  port: 8083

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    playlist:
      # 로컬에서만 사용하므로 평문 사용.
      url: jdbc:postgresql://localhost:5432/${DB_NAME_PLAYLIST}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
  jpa:
    playlist:
      hibernate:
        ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true